import type { Metadata } from "next";
import { Prose } from "@/components/site/Prose";
import thirdParty from "@/lib/legal/third-party.json";

export const metadata: Metadata = { title: "Lizenzen & Datenquellen" };

const CC_BY = "https://creativecommons.org/licenses/by/4.0/deed.de";

/** Data-source credits and open-source notices (generated by scripts/gen-licenses.mjs). */
export default function LicensesPage() {
  return (
    <Prose title="Lizenzen & Datenquellen">
      <h2>Datenquellen</h2>
      <ul>
        <li>
          Wetterdaten: <a href="https://open-meteo.com/">Open-Meteo.com</a>, lizenziert unter{" "}
          <a href={CC_BY}>CC BY 4.0</a>. WitCar rundet die Werte und stellt Wettercodes als Symbole dar.
        </li>
        <li>
          Ortssuche: <a href="https://open-meteo.com/">Open-Meteo.com</a> mit Ortsdaten von{" "}
          <a href="https://www.geonames.org/">GeoNames</a>, lizenziert unter <a href={CC_BY}>CC BY 4.0</a>.
        </li>
        <li>
          Krypto-Kurse: Powered by <a href="https://www.coingecko.com/">CoinGecko</a>.
        </li>
        <li>
          Aktienkurse: <a href="https://finnhub.io/">Finnhub</a>, verzögert.
        </li>
      </ul>
      <p>Ohne konfigurierten Anbieter zeigen die Widgets Demo-Daten und kennzeichnen diese als „Demo-Daten“.</p>

      <h2>Open-Source-Software und Schriften</h2>
      <p>
        WitCar verwendet die folgende Open-Source-Software. Die vollständigen Lizenztexte mit allen Copyright-Hinweisen
        stehen in der Datei{" "}
        <a href="/third-party-licenses.txt" data-testid="license-file">
          third-party-licenses.txt
        </a>
        . Einzelne Symbole im Dashboard sind an <a href="https://lucide.dev">Lucide</a> (ISC-Lizenz) angelehnt.
      </p>
      <div className="overflow-x-auto">
        <table className="w-full text-sm text-left text-dim">
          <thead className="text-text">
            <tr>
              <th className="py-2 pr-4 font-semibold">Paket</th>
              <th className="py-2 pr-4 font-semibold">Version</th>
              <th className="py-2 pr-4 font-semibold">Lizenz</th>
              <th className="py-2 font-semibold">Copyright</th>
            </tr>
          </thead>
          <tbody>
            {thirdParty.map((p) => (
              <tr key={`${p.name}@${p.version}`} className="border-t border-border align-top">
                <td className="py-2 pr-4 min-w-44 wrap-anywhere">
                  {p.homepage ? <a href={p.homepage}>{p.name}</a> : p.name}
                </td>
                <td className="py-2 pr-4 tabular whitespace-nowrap">{p.version}</td>
                <td className="py-2 pr-4 whitespace-nowrap">{p.license}</td>
                <td className="py-2">{p.copyright ?? "—"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Prose>
  );
}
