import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Prose } from "@/components/site/Prose";
import thirdParty from "@/lib/legal/third-party.json";
import { activeSources } from "@/lib/providers";

export const metadata: Metadata = { title: "Lizenzen & Datenquellen" };

const CC_BY = "https://creativecommons.org/licenses/by/4.0/deed.de";

/** Credit per data source id (see src/lib/providers); only live sources are listed. */
const SOURCES: Record<string, ReactNode> = {
  "met-norway": (
    <>
      Wetterdaten: <a href="https://www.met.no/en">MET Norway</a> (Meteorologisk institutt), lizenziert unter{" "}
      <a href={CC_BY}>CC BY 4.0</a>. WitCar rundet die Werte, leitet Tageshöchst- und -tiefstwerte aus der Vorhersage ab
      und stellt Wettercodes als Symbole dar.
    </>
  ),
  "open-meteo": (
    <>
      Wetterdaten: <a href="https://open-meteo.com/">Open-Meteo.com</a>, lizenziert unter <a href={CC_BY}>CC BY 4.0</a>.
      WitCar rundet die Werte und stellt Wettercodes als Symbole dar.
    </>
  ),
  nominatim: (
    <>
      Ortssuche: <a href="https://nominatim.openstreetmap.org/">Nominatim</a>, Daten ©{" "}
      <a href="https://www.openstreetmap.org/copyright">OpenStreetMap-Mitwirkende</a>, lizenziert unter der{" "}
      <a href="https://opendatacommons.org/licenses/odbl/">ODbL</a>.
    </>
  ),
  "open-meteo-geo": (
    <>
      Ortssuche: <a href="https://open-meteo.com/">Open-Meteo.com</a> mit Ortsdaten von{" "}
      <a href="https://www.geonames.org/">GeoNames</a>, lizenziert unter <a href={CC_BY}>CC BY 4.0</a>.
    </>
  ),
  coinmarketcap: (
    <>
      Krypto-Kurse: Daten von <a href="https://coinmarketcap.com/">CoinMarketCap</a>.
    </>
  ),
  coingecko: (
    <>
      Krypto-Kurse: Powered by <a href="https://www.coingecko.com/">CoinGecko</a>.
    </>
  ),
  ecb: (
    <>
      Wechselkurse: Euro-Referenzkurse der{" "}
      <a href="https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html">
        Europäischen Zentralbank (EZB)
      </a>
      . Die Veränderung zum Vortag berechnet WitCar. Referenzkurse dienen nur der Information.
    </>
  ),
  finnhub: (
    <>
      Aktienkurse: <a href="https://finnhub.io/">Finnhub</a>, verzögert.
    </>
  ),
};

/** Data-source credits and open-source notices (generated by scripts/gen-licenses.mjs). */
export default function LicensesPage() {
  const sources = activeSources().filter((id) => SOURCES[id]);
  return (
    <Prose title="Lizenzen & Datenquellen">
      <h2>Datenquellen</h2>
      {sources.length ? (
        <ul>
          {sources.map((id) => (
            <li key={id} data-source={id}>
              {SOURCES[id]}
            </li>
          ))}
        </ul>
      ) : null}
      <p>Ohne konfigurierten Anbieter zeigen die Widgets Demo-Daten und kennzeichnen diese als „Demo-Daten“.</p>

      <h2>Open-Source-Software und Schriften</h2>
      <p>
        WitCar verwendet die folgende Open-Source-Software. Die vollständigen Lizenztexte mit allen Copyright-Hinweisen
        stehen in der Datei{" "}
        <a href="/third-party-licenses.txt" data-testid="license-file">
          third-party-licenses.txt
        </a>
        . Einzelne Symbole im Dashboard sind an <a href="https://lucide.dev">Lucide</a> (ISC-Lizenz) angelehnt.
      </p>
      <div className="overflow-x-auto">
        <table className="w-full text-sm text-left text-dim">
          <thead className="text-text">
            <tr>
              <th className="py-2 pr-4 font-semibold">Paket</th>
              <th className="py-2 pr-4 font-semibold">Version</th>
              <th className="py-2 pr-4 font-semibold">Lizenz</th>
              <th className="py-2 font-semibold">Copyright</th>
            </tr>
          </thead>
          <tbody>
            {thirdParty.map((p) => (
              <tr key={`${p.name}@${p.version}`} className="border-t border-border align-top">
                <td className="py-2 pr-4 min-w-44 wrap-anywhere">
                  {p.homepage ? <a href={p.homepage}>{p.name}</a> : p.name}
                </td>
                <td className="py-2 pr-4 tabular whitespace-nowrap">{p.version}</td>
                <td className="py-2 pr-4 whitespace-nowrap">{p.license}</td>
                <td className="py-2">{p.copyright ?? "—"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Prose>
  );
}
